# Generated by Django 5.2.1 on 2025-05-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E18', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='bioinformatico_agrario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_liderados', to='E18.empleado'),
        ),
    ]
